artifact_location: /home/sigmoid/Desktop/POC/Parallel_RAY/scripts/../mlruns_dir/327790536332618229
creation_time: 1728561468811
experiment_id: '327790536332618229'
last_update_time: 1728561468811
lifecycle_stage: active
name: Stock_Price_Prediction
