artifact_location: /home/sigmoid/Desktop/POC/Parallel_RAY/scripts/../mlruns_dir/0
creation_time: 1728561468797
experiment_id: '0'
last_update_time: 1728561468797
lifecycle_stage: active
name: Default
